### PR TITLE
Add functions to list available maps & to view the mappings for a given map

### PR DESCRIPTION
**Pull request by VishnuSanal**
as mentioned [here](https://github.com/libindic/payyans/issues/17#issuecomment-1826714698)

### CODE REVIEW

**Comment by VishnuSanal** [comment]
@asdofindia PTAL :)

**Comment by asdofindia** [comment]
Ah, I had seen this and forgot to comment.

I was actually talking about listing the maps in the documentation.

But this is probably useful too. 

But @VishnuSanal - these are only functions, right? Can you add a way for the user to call these from the command line?

**Comment by VishnuSanal** [comment]
> I was actually talking about listing the maps in the documentation.

documentation? did you mean [this](https://wiki.smc.org.in/Payyans) wiki page?

> But `@VishnuSanal` - these are only functions, right? Can you add a way for the user to call these from the command line?

um... I didn't quite get you. how to run `payyans` from the terminal? I ran `python -m pip install .` & it got succeeded, but I cannot find neither `payyans` nor `libindic-payyans` commands. pretty sure I am missing something trivial, please help!

**Comment by asdofindia** [comment]
The documentation can be the README file.  The wiki page appears very outdated.

Please see the Usage section in the present documentation. You can add lines to that which runs the functions you added. And also paste the output. That would make it like the maps are there in the README also and people know how to get the maps printed on their own as well

**Comment by asdofindia** [comment]
Thanks

**Pull request merged**
