### PR TITLE
Update build instructions

### PR DESCRIPTION
**Pull request by VishnuSanal**
update build instructions to reflect [this](https://github.com/libindic/payyans/commit/5a862362b32bbfb58774f2d5826f2a82eaf1da91) commit

### CODE REVIEW

**Comment by asdofindia** [comment]
Can you see if build and install can be simplified to one step.

**Comment by VishnuSanal** [comment]
> Can you see if build and install can be simplified to one step.

only way I can find is using `&&` to run both of the commands together. any other pointers?!

**Comment by asdofindia** [comment]
Check other libraries, pip documentation, stackoverflow, etc?

**Comment by asdofindia** [comment]
I saw the emoji. This is the "Installation" instructions, not build instructions. https://pip.pypa.io/en/stable/cli/pip_install/#examples has examples where you can directly install from remote git repo (merging all 4 steps into one).

**Comment by VishnuSanal** [comment]
@asdofindia PTAL

**Pull request merged**
